# Generated by Django 3.2.13 on 2022-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calender', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Documents')),
                ('desc1', models.CharField(max_length=100)),
                ('desc2', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
            ],
        ),
    ]
